photos/urls.py
from django.urls import path

from .views import index, gestante, newborn, acompanhamento, festa, parto, outros

app_name = "photos"
urlpatterns = [
    path("", index, name="index"),
    path("gestante/", gestante, name="gestante"),
    path("newborn/", newborn, name="newborn"),
    path("acompanhamento/", acompanhamento, name="acompanhamento"),
    path("festa/", festa, name="festa"),
    path("parto/", parto, name="parto"),
    path("outros/", outros, name="outros")
]

src/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from .views import index, about

app_name = "www"
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name="index"),
    path('sobre-mim/', about, name="about"),
    path('galeria/', include("photos.urls"))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

photos/models.py
from django.db import models

# Create your models here.


class Categoria(models.Model):
    nome = models.CharField(max_length=64)

    def __str__(self):
        return f"{self.nome}"


class Foto(models.Model):
    titulo = models.CharField(max_length=64)
    categoria = models.ForeignKey(
        Categoria, on_delete=models.CASCADE, related_name="categorias")
    imagem = models.ImageField(upload_to="uploads/")

    def __str__(self):
        return f"{self.titulo} - {self.responsaveis}"

    def delete(self, *args, **kwargs):
        self.imagem.delete()
        super().delete(*args, **kwargs)

photos/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, reverse

from .models import Foto, Categoria

# Create your views here.

app_name = "photos"


def index(request):
    return render(request, "galeria.html")


def gestante(request):
    return render(request, "gestante.html", {
        "pregnant_photos": Foto.objects.filter(categoria__nome__startswith="Gestante")
    })


def newborn(request):
    return render(request, "newborn.html", {
        "newborn_photos": Foto.objects.filter(categoria__nome__startswith="Newborn")
    })


def acompanhamento(request):
    return render(request, "acompanhamento.html", {
        "support_photos": Foto.objects.filter(categoria__nome__startswith="Acompanhamento")
    })


def festa(request):
    return render(request, "festa.html", {
        "party_photos": Foto.objects.filter(categoria__nome__startswith="Festa infantil")
    })


def parto(request):
    return render(request, "parto.html", {
        "born_photos": Foto.objects.filter(categoria__nome__startswith="Parto")
    })


def outros(request):
    return render(request, "outros.html", {
        "other_photos": Foto.objects.filter(categoria__nome__startswith="Outros")
    })

src/views.py
from django.shortcuts import render


def index(request):
    return render(request, "index.html")


def about(request):
    return render(request, "about.html")

www/views.py
from django.shortcuts import render


def index(request):
    return render(request, "index.html")

templates/about.html
{% extends 'layout.html' %}
{% load static %}
{% block title %} Newbaby | Sobre Mim {% endblock title %}
{% block body %}
<div class="photographer">
  <img src="{% static 'images/www/fotografo.jpg' %}" />
</div>
<div class="about-me">
  <h2>Renata Pinheiro</h2>
  <p>
    Me formei em administração de empresas com a dificuldade e persistência de
    quem aos 18 anos precisava trabalhar e estudar para correr atrás dos sonhos
    e da estabilidade financeira. Trabalhei na área financeira de grandes
    empresas por 6 anos sem felicidade. Saí do emprego que me deixava infeliz e
    tentei diversas coisas, mas tudo sem sucesso. Fiquei grávida. Na gravidez da
    primeira filha, Luiza, desejei muito realizar um ensaio fotográfico Newborn,
    porém, sem recursos financeiros, desejei arriscar com uma amiga que tinha o
    equipamento a fazer uma sessão caseira. A partir daí, começou uma procura de
    amigos e conhecidos para realizarmos as fotos de gestantes e de seus bebes.
    Com a demanda aumentando, houve a necessidade de um curso! A partir daí, não
    parei mais! O amor pela fotografia cresceu e tornou-se uma realização de
    vida. Hoje, a New Baby cresce a cada dia no mercado da fotografia atendendo
    a clientes de Uberaba e região. Trabalho com um estilo de fotografia
    clássica. Gosto de pensar que daqui a 10, 20 anos, as fotos que realizei
    hoje não vao parecer bregas ou “fora de moda”. Admiro estilos lúdicos e bem
    contrastados, mas adotei uma fotografia clean e clássica.
  </p>
</div>
{% endblock body %}

templates/acompanhamento.html
{% extends "layout-galeria.html" %}
{% block title %} Newbaby | Ensaio Acompanhamento {%endblock title %}
{% block body %}
<div class="cards">
  {% for photo in support_photos %}
  <div class="card">
    <img src="{{ photo.imagem.url }}" alt="{{ photo.titulo }}" />
    <h3>{{ photo.titulo }}</h3>
  </div>
  {% empty %}
  <h3>Sem fotos no momento.</h3>
  {% endfor %}
</div>
{% endblock body %}

templates/festa.html
{% extends "layout-galeria.html" %}
{% block title %}Newbaby | Ensaio Festa infantil{%endblock title %}
{% block body %}
<div class="cards">
  {% for photo in party_photos %}
  <div class="card">
    <img src="{{ photo.imagem.url }}" alt="{{ photo.titulo }}" />
    <h3>{{ photo.titulo }}</h3>
  </div>
  {% empty %}
  <h3>Sem fotos no momento.</h3>
  {% endfor %}
</div>
{% endblock body %}

templates/galeria.html
{% extends "layout.html" %}
{% load static %}
{% block title %} Newbaby | Galeria {% endblock title %}
{% block body %}
<div class="categories">
  <div class="card">
    <a href="{% url 'photos:gestante' %}">
      <img src="{% static 'images/www/pregnant1.jpg' %}" alt="Gestante" />
      <h3>Ensaio Gestante</h3>
    </a>
  </div>
  <div class="card">
    <a href="{% url 'photos:newborn' %}">
      <img src="{% static 'images/www/newborn1.jpg' %}" alt="Newborn" />
      <h3>Ensaio Newborn</h3>
    </a>
  </div>
  <div class="card">
    <a href="{% url 'photos:festa' %}">
      <img src="{% static 'images/www/party1.jpg' %}" alt="Festa infantil" />
      <h3>Festa infantil</h3>
    </a>
  </div>
  <div class="card">
    <a href="{% url 'photos:acompanhamento' %}">
      <img src="{% static 'images/www/baby2.jpg' %}" alt="Acompanhamento" />
      <h3>Acompanhamento</h3>
    </a>
  </div>
  <div class="card">
    <a href="{% url 'photos:parto' %}">
      <img src="{% static 'images/www/born.jpg' %}" alt="Parto" />
      <h3>Parto</h3>
    </a>
  </div>
  <div class="card">
    <a href="{% url 'photos:outros' %}">
      <img src="{% static 'images/www/outro.jpg' %}" alt="Outros" />
      <h3>Outros</h3>
    </a>
  </div>
</div>
{% endblock body %}

templates/gestante.html
{% extends "layout-galeria.html" %}
{% load static %}
{% block title %}Newbaby | Ensaio Gestante{%endblock title %}
{% block body %}
<div class="cards">
  {% for photo in pregnant_photos %}
  <div class="card">
    <img src="{{ photo.imagem.url }}" alt="{{ photo.titulo }}" />
    <h3>{{ photo.titulo }}</h3>
  </div>
  {% empty %}
  <h3>Sem fotos no momento.</h3>
  {% endfor %}
</div>
{% endblock body %}

templates/index.html
{% extends 'layout.html' %}
{% block title %} NewBaby | Home {% endblock title %}
{% block body %}
<div class="gallery">
  {% load static %}
  <a href="{% url 'photos:index' %}">
    <img src="{% static 'images/www/pregnant2.jpg' %}" alt="Ensaio Gestante" />
  </a>
  <a href="{% url 'photos:index' %}">
    <img src="{% static 'images/www/baby1.jpg' %}" alt="Ensaio Newborn" />
  </a>
  <a href="{% url 'photos:index' %}">
    <img src="{% static 'images/www/party1.jpg' %}" alt="Festa infantil" />
  </a>
  <a href="{% url 'photos:index' %}">
    <img src="{% static 'images/www/pregnant1.jpg' %}" alt="Ensaio Gestante" />
  </a>
  <a href="{% url 'photos:index' %}">
    <img src="{% static 'images/www/baby2.jpg' %}" alt="Ensaio Newborn" />
  </a>
</div>

<hr />

<footer>
  <div class="about">
    <h3>Sobre Mim</h3>
    <p>
      Trabalho com um estilo de fotografia clássica. Gosto de pensar que daqui a
      10, 20 anos, as fotos que realizei hoje não vao parecer bregas ou “fora de
      moda”. Admiro estilos lúdicos e bem contrastados, mas adotei uma
      fotografia clean e clássica.
    </p>
  </div>
  <div class="contact">
    <h3>Entre em contato</h3>
    <p>Telefone: (34) 99145-0828</p>
    <p>Email: newbabyfoto@gmail.com</p>
    <p>Localização: Uberaba/MG</p>
  </div>
</footer>
{% endblock body %}

templates/layout-galeria.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <link
      href="https://fonts.googleapis.com/css?family=Lato:300,400,700|Roboto:400,700&display=swap"
      rel="stylesheet"
    />
    <link rel="stylesheet" href="{% static 'css/photos/styles.css' %}" />
    <title>{% block title %}{% endblock title %}</title>
  </head>

  <body>
    <header id="menu-small">
      <div class="logo">
        <img src="{% static 'images/www/logo.png' %}" alt="Logo" />
      </div>
      <nav>
        <ul>
          <li>
            <a href="{% url 'index' %}">Home</a>
          </li>
          <li>
            <a href="{% url 'photos:index' %}">Galeria</a>
          </li>
          <li>
            <a href="{% url 'about' %}">
              Sobre mim
            </a>
          </li>
        </ul>
      </nav>
      <div class="social-icons">
        <img src="{% static 'images/www/instagram.png' %}" alt="Intagram" />
        <img src="{% static 'images/www/whatsapp.png' %}" alt="Whatsapp" />
        <img src="{% static 'images/www/facebook.png' %}" alt="Facebook" />
      </div>
    </header>
    {% block body %}{% endblock body %}
  </body>
</html>

templates/layout.html
<!DOCTYPE html>
<html lang="pt-BR">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      href="https://fonts.googleapis.com/css?family=Lato:300,400,700|Roboto:400,700&display=swap"
      rel="stylesheet"
    />
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/www/styles.css' %}" />
    <title>{% block title %} {% endblock title %}</title>
  </head>

  <body>
    <div class="main">
      <header id="menu-small">
        <div class="logo">
          <img src="{% static 'images/www/logo.png' %}" alt="Logo" />
        </div>
        <nav>
          <ul>
            <li>
              <a href="{% url 'index' %}">Home</a>
            </li>
            <li>
              <a href="{% url 'photos:index' %}">Galeria</a>
            </li>
            <li>
              <a href="{% url 'about' %}">
                Sobre mim
              </a>
            </li>
          </ul>
        </nav>
        <div class="social-icons">
          <img src="{% static 'images/www/instagram.png' %}" alt="Intagram" />
          <img src="{% static 'images/www/whatsapp.png' %}" alt="Whatsapp" />
          <img src="{% static 'images/www/facebook.png' %}" alt="Facebook" />
        </div>
      </header>
      <header id="menu-large">
        <div class="logo-large">
          <img src="{% static 'images/www/logo.png' %}" alt="Logo" />
        </div>
        <nav>
          <ul>
            <li>
              <a href="{% url 'index' %}">Home</a>
            </li>
            <li>
              <a href="{% url 'photos:index' %}">Galeria</a>
            </li>
            <li>
              <a href="{% url 'about' %}">Sobre mim</a>
            </li>
          </ul>
        </nav>
        <div class="social-icons">
          <img src="{% static 'images/www/instagram.png' %}" alt="Intagram" />
          <img src="{% static 'images/www/whatsapp.png' %}" alt="Whatsapp" />
          <img src="{% static 'images/www/facebook.png' %}" alt="Facebook" />
        </div>
      </header>
      <div class="container">
        {% block body %} {% endblock body %}
      </div>
    </div>
  </body>
</html>

templates/newborn.html
{% extends "layout-galeria.html" %}
{% block title %}Newbaby | Ensaio Newborn{%endblock title %}
{% block body %}
<div class="cards">
  {% for photo in newborn_photos %}
  <div class="card">
    <img src="{{ photo.imagem.url }}" alt="{{ photo.titulo }}" />
    <h3>{{ photo.titulo }}</h3>
  </div>
  {% empty %}
  <h3>Sem fotos no momento.</h3>
  {% endfor %}
</div>
{% endblock body %}

templates/outros.html
{% extends "layout-galeria.html" %}
{% block title %}Newbaby | Outros{%endblock title %}
{% block body %}
<div class="cards">
  {% for photo in other_photos %}
  <div class="card">
    <img src="{{ photo.imagem.url }}" alt="{{ photo.titulo }}" />
    <h3>{{ photo.titulo }}</h3>
  </div>
  {% empty %}
  <h3>Sem fotos no momento.</h3>
  {% endfor %}
</div>
{% endblock body %}

templates/parto.html
{% extends "layout-galeria.html" %}
{% block title %}Newbaby | Ensaio Parto{%endblock title %}
{% block body %}
<div class="cards">
  {% for photo in born_photos %}
  <div class="card">
    <img src="{{ photo.imagem.url }}" alt="{{ photo.titulo }}" />
    <h3>{{ photo.titulo }}</h3>
  </div>
  {% empty %}
  <h3>Sem fotos no momento.</h3>
  {% endfor %}
</div>
{% endblock body %}